In [38]:
import numpy as np

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[0:5] = 100

In [44]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [48]:
slice_of_arr[:] = 99

In [49]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
arr_copy = arr.copy()

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [53]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
arr_2d = np.array(([5,10,15], [20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d[1]

array([20, 25, 30])

In [56]:
arr_2d[1][0]

20

In [57]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr_2d[2]

array([35, 40, 45])

In [59]:
arr2d = np.zeros((0,0))

In [60]:
arr2d

array([], shape=(0, 0), dtype=float64)

In [61]:
arr2d = np.zeros((10,10))

In [62]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [63]:
arr_length = arr2d.shape[1]

In [64]:
arr_length

10

In [65]:
for i in range(arr_length):
    arr2d[i]=i

In [66]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [67]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [70]:
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr[:] = 99

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [23]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [24]:
arr_2d = np.arange(50).reshape(5,10)

In [26]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])