In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.61477414, -0.97638553,  0.43938735,  0.00760142, -1.17618176,
        2.05699491,  0.69509651, -0.88489973,  0.85321499, -0.89976726])

In [8]:
B = np.random.randn(10)
B

array([ 0.18052949,  0.29306612, -0.3296735 , -0.61713529, -0.82060187,
       -0.60654299, -1.53118434, -1.68967111,  2.12231673,  0.54595962])

In [9]:
#Binary Functions
np.add(A,B)

array([-0.43424465, -0.68331941,  0.10971386, -0.60953386, -1.99678363,
        1.45045192, -0.83608783, -2.57457084,  2.97553172, -0.35380764])

In [10]:
np.maximum(A,B)

array([ 0.18052949,  0.29306612,  0.43938735,  0.00760142, -0.82060187,
        2.05699491,  0.69509651, -0.88489973,  2.12231673,  0.54595962])

In [14]:
website = 'http://anthonyhb.com/'
import webbrowser
webbrowser.open(website)

True